version: "3.3"
services: 
  # Watchtower
  watchtower: 
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Wireguard
  wireguard: 
    container_name: wireguard
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "PEERS=2"
      - "PEERDNS=auto"
      - "INTERNAL_SUBNET=10.13.13.0"
      - "ALLOWEDIPS=0.0.0.0/0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: ghcr.io/linuxserver/wireguard:latest
    network_mode: bridge
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/wireguard:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Heimdall
  heimdall: 
    container_name: heimdall
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/heimdall:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/heimdall:/config"
    depends_on:
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # qBittorrent
  qbittorrent: 
    container_name: qbittorrent
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/qbittorrent:/config"
      - "${STORAGE}/downloads:/downloads"
    depends_on:
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Plex
  plex: 
    container_name: plex
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "VERSION=docker"
      - "TZ=${TZ}"
      - "PLEX_CLAIM=${PLEX_CLAIM}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/plex:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/plex:/config"
      - "${STORAGE}/tv-shows:/tv-shows"
      - "${STORAGE}/movies:/movies"
    depends_on:
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Jackett
  jackett: 
    container_name: jackett
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/jackett:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/jackett:/config"
    depends_on:
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Radarr
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/radarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/radarr:/config"
      - "${STORAGE}/movies:/movies"
      - "${STORAGE}/downloads:/downloads"
    depends_on:
      - jackett
      - qbittorrent
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Sonarr
  sonarr: 
    container_name: sonarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/sonarr:/config"
      - "${STORAGE}/tv-shows:/tv-shows"
      - "${STORAGE}/downloads:/downloads"
    depends_on:
      - jackett
      - qbittorrent
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Bazarr
  bazarr: 
    container_name: bazarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - "${DOCKER}/bazarr:/config"
      - "${STORAGE}/tv-shows:/tv-shows"
      - "${STORAGE}/movies:/movies"
    depends_on:
      - sonarr
      - radarr
      - wireguard
    labels:
      - "com.centurylinklabs.watchtower.enable=true"