version: "3.3"
services: 
  # Watchtower
  watchtower: 
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Wireguard
  wireguard: 
    container_name: wireguard
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: ghcr.io/linuxserver/wireguard:latest
    network_mode: bridge
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Heimdall
  heimdall: 
    container_name: heimdall
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/heimdall:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/heimdall:/config
    depends_on:
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # qBittorrent
  qbittorrent: 
    container_name: qbittorrent
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/qbittorrent:/config
      - ${STORAGE:-/storage}:/storage
    depends_on:
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Plex
  plex: 
    container_name: plex
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - VERSION=docker
      - TZ=${TZ:-Etc/GMT}
      - PLEX_CLAIM=${PLEX_CLAIM}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/plex:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/plex:/config
      - ${STORAGE:-/storage}:/storage
    depends_on:
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Jackett
  jackett: 
    container_name: jackett
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/jackett:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/jackett:/config
    depends_on:
      - flaresolverr
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Radarr
  radarr: 
    container_name: radarr
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/radarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/radarr:/config
      - ${STORAGE:-/storage}:/storage
    depends_on:
      - jackett
      - qbittorrent
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Sonarr
  sonarr: 
    container_name: sonarr
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/sonarr:/config
      - ${STORAGE:-/storage}:/storage
    depends_on:
      - jackett
      - qbittorrent
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Bazarr
  bazarr: 
    container_name: bazarr
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER:-/opt}/bazarr:/config
      - ${STORAGE:-/storage}:/storage
    depends_on:
      - sonarr
      - radarr
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # FlareSolverr
  flaresolverr: 
    container_name: flaresolverr
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/GMT}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: service:wireguard
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true